# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dataset": "00_utils.data.dataset.ipynb",
         "get_train_val_split": "00_utils.data.dataset.ipynb",
         "DataLoaders": "01_utils.data.dataloaders.ipynb",
         "show_image": "02_utils.vizualize.ipynb",
         "plot_loss_update": "02_utils.vizualize.ipynb",
         "plot_lr": "02_utils.vizualize.ipynb",
         "Callbacks": "03_callbacks.ipynb",
         "SetupLearnerCB": "03_callbacks.ipynb",
         "Recorder": "03_callbacks.ipynb",
         "ShowStats": "03_callbacks.ipynb",
         "TrackTrainVal": "03_callbacks.ipynb",
         "AvgMetric": "03_callbacks.ipynb",
         "AccumMetric": "03_callbacks.ipynb",
         "AvgLosses": "03_callbacks.ipynb",
         "AvgSmoothLoss": "03_callbacks.ipynb",
         "Learner": "04_learner.ipynb",
         "random_seed": "04_learner.ipynb",
         "accuracy": "05_metrics.ipynb",
         "error_rate": "05_metrics.ipynb",
         "precision": "05_metrics.ipynb",
         "recall": "05_metrics.ipynb",
         "f1score": "05_metrics.ipynb",
         "confusion_matrix": "05_metrics.ipynb",
         "plot_confusion_matrix": "05_metrics.ipynb"}

modules = ["utils/data/dataset.py",
           "utils/data/dataloaders.py",
           "utils/vizualize.py",
           "callbacks.py",
           "learner.py",
           "metric.py"]

doc_url = "https://vedant.github.io/PrimeCNNv3/"

git_url = "https://github.com/vedant/PrimeCNNv3/tree/master/"

def custom_doc_links(name): return None
