# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://vedant.github.io/PrimeCNNv3/"

git_url = "https://github.com/vedant/PrimeCNNv3/tree/master/"

def custom_doc_links(name): return None
