# AUTOGENERATED! DO NOT EDIT! File to edit: 02_utils.vizualize.ipynb (unless otherwise specified).

__all__ = ['show_image', 'plot_loss_update', 'plot_lr']

# Cell
from ..imports import *

# Cell
def show_image(image,ax = None, title = None, figsize = (5,5)):
    '''shows a single image'''

    if ax is None: _, ax = plt.subplots(figsize = figsize)

    if title is not None : ax.set_title(title)

    ax.imshow(image)
    ax.axis('off')

    plt.show()

# Cell

def plot_loss_update(nbs_batches,epochs, mb, train_loss, valid_loss):
    '''
        Dynamic loss plot during training
        epoch to start from 1
    '''
    graphs = [(range(len(train_loss)),train_loss), (nbs_batches,valid_loss)]
   # graphs = [(range(1, len(train_loss)+1),train_loss)]

    x_bounds= (0,(epochs - len(nbs_batches)) * nbs_batches[0] + len(train_loss))
    y_bounds = (0, max(max(train_loss),max(valid_loss)))

    mb.update_graph(graphs,x_bounds, y_bounds, figsize = (6,4)) #add margin

    plt.show()

# Cell
def plot_lr(lrs, losses):
    '''
        Plot lr vs loss graphs
    '''
    _,ax = plt.subplots(1,1, figsize= (6,4))
    ax.set_xlabel('lrs')
    ax.set_ylabel('Loss')
    ax.set_xscale('log')
    ax.plot(lrs[:-2],losses[:-2])
    plt.show()